// Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.8.1 (stable) (Wed May 28 00:47:25 2025 -0700) on "windows_x64"
// Module: packages/moniter/pages/daily_journal_page.dart
// Flags: enableAsserts(true)
define(['dart_sdk', 'packages/flutter/src/cupertino/text_form_field_row.dart', 'packages/moniter/components/financial_report/base_report_page.dart'], (function load__packages__moniter__pages__daily_journal_page_dart(dart_sdk, packages__flutter__src__cupertino__text_form_field_row$46dart, packages__moniter__components__financial_report__base_report_page$46dart) {
  'use strict';
  const dart_rti = dart_sdk.dart_rti;
  const core = dart_sdk.core;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const widget_inspector = packages__flutter__src__cupertino__text_form_field_row$46dart.flutter__src__widgets__widget_inspector;
  const framework = packages__flutter__src__cupertino__text_form_field_row$46dart.flutter__src__widgets__framework;
  const base_report_page = packages__moniter__components__financial_report__base_report_page$46dart.moniter__components__financial_report__base_report_page;
  var daily_journal_page = Object.create(dart.library);
  const CT = Object.create({
    _: () => (C, CT)
  });
  dart.defineLazy(CT, {
    get C0() {
      return C[0] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "DailyJournalPage",
        [_Location_column]: 9,
        [_Location_line]: 5,
        [_Location_file]: "file:///D:/flutter/projects/monitor/lib/pages/daily_journal_page.dart"
      }, widget_inspector._Location.prototype));
    },
    get C2() {
      return C[2] = dart.const(Object.setPrototypeOf({
        [_Location_name]: "BaseReportPage",
        [_Location_column]: 18,
        [_Location_line]: 20,
        [_Location_file]: "file:///D:/flutter/projects/monitor/lib/pages/daily_journal_page.dart"
      }, widget_inspector._Location.prototype));
    },
    get C3() {
      return C[3] = dart.constList(dart_rti._Universe.eval(dart_rti._theUniverse(), "core|String", true), ["ทุกสมุดรายวัน", "ทั่วไป", "จ่าย", "รับ", "ซื้อ", "ขาย", "ธนาคาร", "ไม่บันทึกบัญชี"]);
    },
    get C1() {
      return C[1] = dart.const(Object.setPrototypeOf({
        [Widget__location]: C[2] || CT.C2,
        [Widget_key]: null,
        [BaseReportPage_defaultReportType]: null,
        [BaseReportPage_reportTypes]: C[3] || CT.C3,
        [BaseReportPage_title]: "สมุดรายวัน (Daily Journal)"
      }, base_report_page.BaseReportPage.prototype));
    }
  });
  var C = Array(4).fill(void 0);
  var I = [
    "package:moniter/pages/daily_journal_page.dart",
    "dart:core"
  ];
  var _Location_name = dart.privateName(widget_inspector, "_Location.name");
  var _Location_column = dart.privateName(widget_inspector, "_Location.column");
  var _Location_line = dart.privateName(widget_inspector, "_Location.line");
  var _Location_file = dart.privateName(widget_inspector, "_Location.file");
  var Widget__location = dart.privateName(framework, "Widget._location");
  var Widget_key = dart.privateName(framework, "Widget.key");
  var BaseReportPage_defaultReportType = dart.privateName(base_report_page, "BaseReportPage.defaultReportType");
  var BaseReportPage_reportTypes = dart.privateName(base_report_page, "BaseReportPage.reportTypes");
  var BaseReportPage_title = dart.privateName(base_report_page, "BaseReportPage.title");
  daily_journal_page.DailyJournalPage = class DailyJournalPage extends framework.StatelessWidget {
    static ['_#new#tearOff'](opts) {
      let key = opts && 'key' in opts ? opts.key : null;
      return new daily_journal_page.DailyJournalPage.new({key: key, $creationLocationd_0dea112b090073317d4: C[0] || CT.C0});
    }
    build(context) {
      return C[1] || CT.C1;
    }
  };
  (daily_journal_page.DailyJournalPage.new = function(opts) {
    let key = opts && 'key' in opts ? opts.key : null;
    let $36creationLocationd_0dea112b090073317d4 = opts && '$creationLocationd_0dea112b090073317d4' in opts ? opts.$creationLocationd_0dea112b090073317d4 : null;
    dart.global.Object.getPrototypeOf(daily_journal_page.DailyJournalPage).new.call(this, {key: key, $creationLocationd_0dea112b090073317d4: $36creationLocationd_0dea112b090073317d4});
    ;
  }).prototype = daily_journal_page.DailyJournalPage.prototype;
  dart.lazyFn(daily_journal_page.DailyJournalPage['_#new#tearOff'], () => dart_rti._Universe.eval(dart_rti._theUniverse(), "moniter__pages__daily_journal_page|DailyJournalPage({key:flutter__src__foundation__key|Key?})", true));
  dart.addRtiResources(daily_journal_page.DailyJournalPage, ["moniter__pages__daily_journal_page|DailyJournalPage"]);
  dart.setMethodSignature(daily_journal_page.DailyJournalPage, () => dart.global.Object.setPrototypeOf({
    build: _ti => dart_rti._Universe.eval(dart_rti._theUniverse(), "flutter__src__widgets__framework|Widget(flutter__src__widgets__framework|BuildContext)", true)
  }, dart.getMethods(dart.global.Object.getPrototypeOf(daily_journal_page.DailyJournalPage))));
  dart.setMethodsImmediateTargetSignature(daily_journal_page.DailyJournalPage, () => dart.global.Object.setPrototypeOf({build: "package:moniter/pages/daily_journal_page.dart:DailyJournalPage"}, dart.getMethodsImmediateTargets(dart.global.Object.getPrototypeOf(daily_journal_page.DailyJournalPage))));
  dart.setLibraryUri(daily_journal_page.DailyJournalPage, I[0]);
  dart.setStaticFieldSignature(daily_journal_page.DailyJournalPage, () => ['_reportTypes']);
  dart.defineLazy(daily_journal_page.DailyJournalPage, {
    /*daily_journal_page.DailyJournalPage._reportTypes*/get _reportTypes() {
      return C[3] || CT.C3;
    }
  });
  dart.moduleConstCaches.set("packages/moniter/pages/daily_journal_page.dart", C);
  dart_rti._Universe.addRules(dart.typeUniverse, JSON.parse('{"core|String":{"Comparable.T":"core|String","core|Comparable":["core|String"],"core|Pattern":[]},"core|Comparable":{"Comparable.T":"1"},"moniter__pages__daily_journal_page|DailyJournalPage":{"flutter__src__widgets__framework|StatelessWidget":[],"flutter__src__widgets__framework|Widget":[],"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]},"flutter__src__widgets__framework|StatelessWidget":{"flutter__src__widgets__framework|Widget":[],"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]},"flutter__src__widgets__framework|Widget":{"flutter__src__foundation__diagnostics|DiagnosticableTree":[],"flutter__src__widgets__widget_inspector|_HasCreationLocation":[],"flutter__src__foundation__diagnostics|Diagnosticable":[]},"flutter__src__foundation__diagnostics|DiagnosticableTree":{"flutter__src__foundation__diagnostics|Diagnosticable":[]},"core|List":{"List.E":"1","Iterable.E":"1","core|Iterable":["1"],"_ListIterable.E":"1","core|_ListIterable":["1"],"EfficientLengthIterable.T":"1","_internal|EfficientLengthIterable":["1"],"HideEfficientLengthIterable.T":"1","_internal|HideEfficientLengthIterable":["1"]},"core|Iterable":{"Iterable.E":"1"},"core|_ListIterable":{"_ListIterable.E":"1","EfficientLengthIterable.T":"1","_internal|EfficientLengthIterable":["1"],"HideEfficientLengthIterable.T":"1","_internal|HideEfficientLengthIterable":["1"],"Iterable.E":"1","core|Iterable":["1"]},"_internal|EfficientLengthIterable":{"EfficientLengthIterable.T":"1","Iterable.E":"1","core|Iterable":["1"]},"_internal|HideEfficientLengthIterable":{"HideEfficientLengthIterable.T":"1","Iterable.E":"1","core|Iterable":["1"]}}'));
  dart.trackLibraries("packages/moniter/pages/daily_journal_page.dart", {
    "package:moniter/pages/daily_journal_page.dart": daily_journal_page
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["daily_journal_page.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;UAkB4B;AACxB;IAIF;;;QAnB8B;;AAAxB,gGAAwB,GAAG;;EAAE;;;;;;;;;;MAET,gDAAY","file":"../../../../../packages/moniter/pages/daily_journal_page.dart.lib.js"}');
  // Exports:
  return {
    moniter__pages__daily_journal_page: daily_journal_page
  };
}));

//# sourceMappingURL=daily_journal_page.dart.lib.js.map
